# Generated by Django 5.2.2 on 2025-06-07 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='author',
            field=models.CharField(default='Desconocido', max_length=100),
            preserve_default=False,
        ),
    ]
