# Generated by Django 5.2.2 on 2025-06-08 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_product_author'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
